######################################################################
##
## Filename: ac97_if.udo
## Created on: Sat Feb 09 7:16:01 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
