######################################################################
##
## Filename: i2c_sender.udo
## Created on: Mon Feb 11 8:10:44 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
