######################################################################
##
## Filename: i2c_emulator.udo
## Created on: Mon Feb 11 5:11:23 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
