######################################################################
##
## Filename: lab4_top.udo
## Created on: Mon Feb 11 2:59:20 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
