######################################################################
##
## Filename: mcu.udo
## Created on: Mon Feb 11 11:08:57 AM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
