######################################################################
##
## Filename: mcu_tb.udo
## Created on: Mon Feb 11 10:58:52 AM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
