######################################################################
##
## Filename: music_player_tb.udo
## Created on: Sat Feb 09 3:28:27 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
