######################################################################
##
## Filename: note_player_tb.udo
## Created on: Wed Feb 13 6:21:44 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
