######################################################################
##
## Filename: sine_reader.udo
## Created on: Sat Feb 09 7:31:43 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
