######################################################################
##
## Filename: song_reader_tb.udo
## Created on: Sat Feb 09 7:00:47 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
