######################################################################
##
## Filename: wave_capture_tb.udo
## Created on: Sat Feb 16 2:08:53 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
