######################################################################
##
## Filename: wave_display.udo
## Created on: Sun Feb 17 4:08:15 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
