######################################################################
##
## Filename: wave_display_tb.udo
## Created on: Mon Feb 18 4:38:54 PM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
