######################################################################
##
## Filename: wave_display_top_tb.udo
## Created on: Sun Feb 17 11:39:32 AM Pacific Standard Time 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
